### ISSUE TITLE
main.py 运行一段时间就出错

### ISSUE THREAD

**Issue by YuiGuizhichen** [Dwayneten/JGM-Automator#5]
我读不懂代码，所以贴错误信息问问该如何解决，希望得到你的帮助！

> read_params_file: parameter not found: ??
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\win\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\win\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Documents\JGM-Automator-master\main.py", line 15, in main
    instance.start()
  File "F:\Documents\JGM-Automator-master\automator.py", line 213, in start
    self._upgrade()
  File "F:\Documents\JGM-Automator-master\automator.py", line 335, in _upgrade
    need_upgrade_building_seq = self._select_min_building()
  File "F:\Documents\JGM-Automator-master\automator.py", line 307, in _select_min_building
    txt = UIMatcher.image_to_txt(tmp, plus='-l chi_sim --psm 7')
  File "F:\Documents\JGM-Automator-master\cv.py", line 79, in image_to_txt
    txt_name + ' ' + plus, shell=True)  # 生成同名txt文件
  File "C:\Users\win\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "C:\Users\win\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'tesseract --dpi 72 ./tmp/tmp.jpg ./tmp/tmp -l chi_sim --psm 7' returned non-zero exit status 1.

**Comment by Dwayneten** [comment]
是不是没有装 tesseract 呢
这个是旧版自动升级时用到的 如果要用的话需要装 tesseract
如果不需要自动升级的话 可以在`automater.py`里207行左右把这段注释掉
```python
# 升级建筑
"""
tmp_upgrade_interval = time.time() - tmp_upgrade_last_time
    if tmp_upgrade_interval >= self.config.upgrade_interval_sec:
        if self.config.upgrade_type_is_assign is True:
            self._assigned_uprade()
        else:
            self._upgrade()
        tmp_upgrade_last_time = time.time()
    else:
        logger.info(f"Left {round(self.config.upgrade_interval_sec - tmp_upgrade_interval, 2)}s to upgrade")
"""
```

如果需要自动升级
更推荐的方法是在`config.json`里
```JavaScript
"upgrade_type_is_assign": true, // true
"assigned_building_pos": 7,       // 填你主力建筑的位置编号
```

**Comment by YuiGuizhichen** [comment]
你好，尝试注释这段代码后，成功运行了。
至于 tesseract 我按照网上的方法安装并配置好了 Path，估计因为我没重启所以没生效吗？

**Comment by Dwayneten** [comment]
@YuiGuizhichen 是什么版本的`tesseract`呢，我用的 5.0 从 https://github.com/UB-Mannheim/tesseract/wiki 下的

**Comment by YuiGuizhichen** [comment]
你好！是官网的安装包，版本是 4.0 ，exe 安装版本！
