### ISSUE TITLE
你好,运行升级建筑的命令提示这个,请问是什么问题?

### ISSUE THREAD

**Issue by soamber** [Dwayneten/JGM-Automator#6]
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\soamber\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\soamber\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "E:\辅助\JGM-Automator-master\main.py", line 15, in main
    instance.start()
  File "E:\辅助\JGM-Automator-master\automator.py", line 142, in start
    if not self._need_continue():
  File "E:\辅助\JGM-Automator-master\automator.py", line 80, in _need_continue
    self._upgrade_to(target_level)
  File "E:\辅助\JGM-Automator-master\automator.py", line 367, in _upgrade_to
    tmp = UIMatcher.plain(tmp)
  File "E:\辅助\JGM-Automator-master\cv.py", line 107, in plain
    erode = cv2.erode(image, kernel)
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\core\src\matrix.cpp:757: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'cv::Mat::locateROI'

**Comment by soamber** [comment]
刚才忘记说了,机器安装了Tesseract OCR,并且添加了路径,在CMD中能查到版本号,其余命令输入正常,在输入升级建筑 run upgrade_to 500 的时候就出现这个提示了!

**Comment by qq4199** [comment]
同样这个命令报错，安装了tesseractocr，环境变量也配置完成，cmd也能运行，但运行这个就是不行，其他命令可以

run upgrade_to 1099
'tesseract' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\game\JGM\dan\main.py", line 15, in main
    instance.start()
  File "D:\game\JGM\dan\automator.py", line 142, in start
    if not self._need_continue():
  File "D:\game\JGM\dan\automator.py", line 80, in _need_continue
    self._upgrade_to(target_level)
  File "D:\game\JGM\dan\automator.py", line 370, in _upgrade_to
    txt = UIMatcher.image_to_txt(tmp, plus='-l chi_sim --psm 7')
  File "D:\game\JGM\dan\cv.py", line 79, in image_to_txt
    txt_name + ' ' + plus, shell=True)  # 生成同名txt文件
  File "C:\Program Files\Python36\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python36\lib\subprocess.py", line 437, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'tesseract --dpi 72 ./tmp/tmp.jpg ./tmp/tmp -l chi_sim --psm 7' returned non-zero exit status 1.

**Comment by Dwayneten** [comment]
这其实是两个不同的问题

@soamber 的看起来是
`erode = cv2.erode(image, kernel)`
执行的时候读不了 image
不知道前面截图的时候有没有截成功
把`automator.py` 365 和 366 行注释去掉 输出截图看看？


@qq4199 的报错信息里面有说

> 'tesseract' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。

 `tesseract` 有没有安装成功并且添加到环境变量
cmd 里能运行吗


不过两个问题都可以暂时用`run upgrade_times x`这个命令代替
这个命令不需要用到`tesseract`

**Comment by qq4199** [comment]
> 这其实是两个不同的问题
> 
> @soamber 的看起来是
> `erode = cv2.erode(image, kernel)`
> 执行的时候读不了 image
> 不知道前面截图的时候有没有截成功
> 把`automator.py` 365 和 366 行注释去掉 输出截图看看？
> 
> @qq4199 的报错信息里面有说
> 
> > 'tesseract' 不是内部或外部命令，也不是可运行的程序
> > 或批处理文件。
> 
> `tesseract` 有没有安装成功并且添加到环境变量
> cmd 里能运行吗
> 
> 不过两个问题都可以暂时用`run upgrade_times x`这个命令代替
> 这个命令不需要用到`tesseract`

安装成功了添加到环境变量里了，cmd运行tesseract也能成功

**Comment by Dwayneten** [comment]
@qq4199 那你可以试下
```python
# cv.py 179 行
subprocess.check_output('tesseract --dpi 72 ' + image_url + ' ' + txt_name + ' ' + plus, shell=True)
```
里的`shell=True`改成`shell=False` 试试，如果不行我也不知道是什么原因

**Comment by qq4199** [comment]
> @qq4199 那你可以试下
> 
> ```python
> # cv.py 179 行
> subprocess.check_output('tesseract --dpi 72 ' + image_url + ' ' + txt_name + ' ' + plus, shell=True)
> ```
> 
> 里的`shell=True`改成`shell=False` 试试，如果不行我也不知道是什么原因

解决了，python安装了3.7。4就可以了，之前用的3.6的
