### ISSUE TITLE
Opencv报OutOfMemory

### ISSUE THREAD

**Issue by kevinfu2** [Dwayneten/JGM-Automator#8]
用的Mumu模拟器，刷金币的时间间隔设为0，运行火车只收橙半小时左右就会出现
电脑是8G内存，模拟器默认配置4G内存

`
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Program Files\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\github\python\JGM-Automator\main.py", line 15, in main
    instance.start()
  File "D:\github\python\JGM-Automator\automator.py", line 166, in start
    has_goods |= self._match_target(screen, target)
  File "D:\github\python\JGM-Automator\automator.py", line 249, in _match_target
    result = UIMatcher.match(screen, target)
  File "D:\github\python\JGM-Automator\cv.py", line 39, in match
    res = cv2.matchTemplate(screen, template, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\core\src\alloc.cpp:72: error: (-4:Insufficient memory) Failed to allocate 49838424 bytes in function 'cv::OutOfMemoryError'
`
感觉和uiautomator2的这个bug有关 [截图导致模拟器死机，怎么解决？](https://github.com/openatx/uiautomator2/issues/385)

**Comment by Dwayneten** [comment]
MuMu 模拟器 3G 内存 默认手机型号没遇到这种情况

唯一一次报 outofmemory 是因为断网了 一直在截图检测有没有进入游戏界面..

重启模拟器关掉重启刷新火车看看会不会解决

如果是 uiautomator2 的问题的话 我也解决不了

**Comment by kevinfu2** [comment]
谢谢！突然就好了，先关闭了

是minicap引起的，删除minicap后再启动main就好了

adb shell rm /data/local/tmp/minicap
adb shell rm /data/local/tmp/minicap.so
